# Generated by Django 6.0.5 on 2026-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_lesson_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hours', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
    ]
