# Generated by Django 6.0.5 on 2026-05-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schoolsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='price_per_hours',
            new_name='price_per_hour',
        ),
    ]
